spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${secrets.oauth.google.client-id}
            client-secret: ${secrets.oauth.google.client-secret}
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            scope:
              - email
              - profile
          naver:
            client-id: ${secrets.oauth.naver.client-id}
            client-secret: ${secrets.oauth.naver.client-secret}
            redirect-uri: "{baseUrl}/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
            client-name: Naver
            provider: naver
          kakao:
            client-id: ${secrets.oauth.kakao.client-id}
            client-secret: ${secrets.oauth.kakao.client-secret}
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
            client-name: Kakao
            client-authentication-method: client_secret_post
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
